site_name: Bailey Bignall
site_url: https://thatbooradley.github.io/

#locale: en
#time_format: '%Y-%m-%d %H:%M:%S'
#meta_time_format: '%Y-%m-%d %H:%M:%S'

nav:
  - Home: index.md
  - Writing:
    - msf/index.md

#theme:

plugins:
  #- social
  - blogging:
      theme:
        name: card
      locale: en
      dirs:
        - msf
    # post_url_format: "{slug}"
