site_name: Knothole
site_url: https://thatbooradley.github.io/

nav:
  - Home: index.md
  - About: about.md
  - Itch.io: https://boo-radley.itch.io/
  - Github: https://github.com/ThatBooRadley
  - ...
 
theme:
  name: material
  font:
    text: Trebuchet
  logo: ghost.svg
  favicon: ghost.ico
  features:
    - navigation.tabs
    - navigation.footer
  palette:
    primary: brown
    accent: lime


markdown_extensions:
  - smarty
  - nl2br
  - extra
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 0

plugins:
  - awesome-pages
